name: Javascript Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/internals/setup-js

  unit-tests:
    needs: setup
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inst/ui-editor-react
    steps:
      - uses: ./.github/internals/setup-js
      - name: Run unit tests
        run: yarn test run

  playwright-tests:
    needs: setup
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inst/ui-editor-react
    steps:
      - uses: ./.github/internals/setup-js

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: ./inst/ui-editor-react/playwright-report/
          retention-days: 30

  check-if-current-build:
    needs: setup
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inst/ui-editor-react
    steps:
      - uses: ./.github/internals/setup-js

      - name: Check if build is current
        run: |
          yarn build
          # If this fails then the build is stale compared to source
          git diff --exit-code -- build/

  build-pkgdown-site:
    needs: setup
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: ./.github/internals/setup-js

      - name: Build demo app for site
        working-directory: ./inst/ui-editor-react
        run: yarn build-website-demo

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Make sure entire demo app has been copied to articles/
        run: cp -r vignettes/demo-app docs/articles/

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
