name: Javascript Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inst/ui-editor-react
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: ./inst/ui-editor-react/playwright-report/
          retention-days: 30
      - name: Run unit tests
        run: yarn test run
      - name: Check if build is current
        run: |
          yarn build
          # If this fails then the build is stale compared to source
          git diff --quiet ./inst/ui-editor-react/build/
